language: python
cache: pip
sudo: required

python:
  - "3.6"

install:
  - sudo apt-get update -y && apt-get install -y cmake
  - pip install mypy
  - pip install . -v

script:
  - mypy -m cuckoo
  - python3 -m unittest discover -v -s test

notifications:
  email:
    on_failure: change
    on_success: never