language: python
cache: pip
sudo: required

python:
  - "3.6"

matrix:
  include:
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7
#
#    # Clang on OS X
#    - os: osx
#      osx_image: xcode10.1
#
#    - os: osx
#      osx_image: xcode9.4

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - gcc
          update: true

install:
  - pip install mypy cmake --upgrade
  - pip install .

#script:
#  - mypy -m cuckoo
#  - python3 -m unittest discover -v -s test

notifications:
  email:
    on_failure: change
    on_success: never